### ISSUE TITLE
İlginç bir sorun

### ISSUE THREAD

**Issue by necoakdogan** [payconn/ipara#12]
Merhaba. Kütüphanenizi kullanarak gerçek ortamda 1 tl lik ödeme yapıldı (3d ile kod girerek). Sonuç başarılı olup success sayfasına yönlendirilmesine rağmen ne karttan para çekildi ne de ipara paneline sipariş düştü. Sizce sorun nedir? Sonuç olarak 3d ile güvenlik koduda girilmesine rağmen bu şekilde oldu. Şimdiden teşekkürler.

**Comment by muratsac** [comment]
Merhaba,

3D işlemi iki aşamadan oluşmaktadır. 

1. Aşamada kredi kartı sahibi banka ekranına yönlendirilerek kartına yetki verir. Bu işlem için `authorize` adımı uygulanır.
2. Aşama ise bankadan success sayfasına döndükten sonra, dönen parametrelerle ödemenin tamamlanması aşamasıdır. Bu aşama da `complate` adımı uygulanarak ödeme tamamlanır. 

Anlattığınıza göre başarılı sayfasına geldikten sonra complete işlemini yapmıyorsunuz. Yani ödeme yarım kalıyor. Bu adımı da eklerseniz sorun düzelecektir. 

https://payconn.github.io/ipara#complete
