### ISSUE TITLE
amount gönderim sorunu

### ISSUE THREAD

**Issue by necoakdogan** [payconn/ipara#13]
Merhaba. Size bir soru sormak istiyorum. Sepetteki  ürünlerin tutarı 2.755.91 TL diyelim. Bunu amount değeri olarak nasıl  göndermem gerek? Çünkü 2.00 TL olarak gönderiyor. Cevabınızı veya yön göstermenizi rica edeceğim.
İyi çalışmalar dilerim.

**Comment by muratsac** [comment]
Merhaba,

`2755.91` şeklinde gönderirseniz sorun çözülecektir. 

Kolay gelsin.

**Comment by necoakdogan** [comment]
Cevap için teşekkür ederim. Test edeceğim.
İyi çalışmalar.

**Comment by muratsac** [comment]
https://payconn.github.io/ipara buradaki dokümandan yararlanabilirsiniz.
